language: scala
scala:
  - 2.10.4

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d7d25eec49bfe73a4f9b
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: always    # options: [always|never|change] default: always

script:
  - sbt test assembly doc

deploy:
  provider: releases
  api_key:
    secure: EgJ7RuEBzNjcKBuQP4jtwPU1hp8LzoacGufAaimOfG4+3pTfbPFttXjMXjb/8HP4QF1vcFH3BemPyZng20qTTP1LuoNvU3Ae4ZakCFDS0F9KfajibcmJRCqoJ7LSI6olFS/zyMWNVWkEUiBcOcLIafBTz1HB6M0ucxanN6/dUS4=
  file: "target/scala-*/konstructs-server-*.jar"
  file_glob: true
  on:
    repo: konstructs/server
    tags: true
